-- AlterTable
ALTER TABLE "University" ADD COLUMN     "qsRanking" INTEGER,
ADD COLUMN     "universityAverageScholarship" DECIMAL(65,30),
ADD COLUMN     "universityAverageScholarshipRemarks" TEXT,
ADD COLUMN     "universityLogoExtension" TEXT,
ADD COLUMN     "usNewsRanking" INTEGER,
ADD COLUMN     "webomatricsNationalRanking" INTEGER,
ADD COLUMN     "webomatricsWorldRanking" INTEGER;

-- CreateTable
CREATE TABLE "Program" (
    "id" TEXT NOT NULL,
    "sourceId" INTEGER NOT NULL,
    "universityId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "concentration" TEXT,
    "studyLevelId" INTEGER,
    "studyLevel" TEXT,
    "categoryId" TEXT,
    "subCategoryId" TEXT,
    "isStemCourse" BOOLEAN,
    "isOnlineCourse" BOOLEAN,
    "isExtraChoicesOfPrograms" BOOLEAN,
    "highlights" TEXT,
    "universityOrder" INTEGER,
    "durationMonths" INTEGER,
    "campus" TEXT,
    "countryId" INTEGER,
    "cohortCountryCode" TEXT,
    "amount" DECIMAL(65,30),
    "tuitionFeeText" TEXT,
    "currencyCode" TEXT,
    "currency" TEXT,
    "tuitionFeeCurrency" TEXT,
    "applicationFee" TEXT,
    "applicationFeeAmt" DECIMAL(65,30),
    "applicationFeeCurrency" TEXT,
    "appFeeWaiverAvailable" BOOLEAN,
    "depositCurrency" TEXT,
    "depositSortAmount" DECIMAL(65,30),
    "courseDeposit" JSONB,
    "universityDeposit" JSONB,
    "intakes" TEXT[],
    "displayIntakes" TEXT[],
    "applicationDeadline" TEXT,
    "applicationDeadlineDetails" TEXT,
    "intakesAndDeadlines" TEXT,
    "upcomingIntakeDeadLines" TEXT,
    "intakesClosed" TEXT,
    "applicationMode" TEXT,
    "applicationCount12Mo" INTEGER,
    "ieltsOverall" DOUBLE PRECISION,
    "ieltsNoBandLessThan" DOUBLE PRECISION,
    "ieltsRequired" BOOLEAN,
    "ieltsWaiverScoreCBSE" DOUBLE PRECISION,
    "ieltsWaiverScoreState" DOUBLE PRECISION,
    "pteScore" INTEGER,
    "pteNoSectionLessThan" INTEGER,
    "pteRequired" BOOLEAN,
    "toeflScore" INTEGER,
    "toeflNoSectionLessThan" INTEGER,
    "toeflRequired" BOOLEAN,
    "detScore" INTEGER,
    "detRequired" BOOLEAN,
    "greScore" INTEGER,
    "greRequired" BOOLEAN,
    "gmatScore" INTEGER,
    "gmatRequired" BOOLEAN,
    "satScore" INTEGER,
    "satRequired" BOOLEAN,
    "actScore" INTEGER,
    "actRequired" BOOLEAN,
    "withoutEnglishProficiency" BOOLEAN,
    "englishMarks12Score" DOUBLE PRECISION,
    "isMOIWaiver" BOOLEAN,
    "elpAvailable" BOOLEAN,
    "eslAvailable" BOOLEAN,
    "eslElpDetail" TEXT,
    "entryRequirement" TEXT,
    "entryRequirementTwelfth" TEXT,
    "entryRequirementTwelfthOutOf100" TEXT,
    "entryRequirementTwelfthOutOf45" TEXT,
    "entryRequirementTwelfthOutOf10" TEXT,
    "entryRequirementTwelfthOutOf7" TEXT,
    "entryRequirementTwelfthOutOf5" TEXT,
    "entryRequirementTwelfthOutOf4" TEXT,
    "entryRequirementUG" TEXT,
    "entryRequirementUgOutOf100" TEXT,
    "entryRequirementUgOutOf10" TEXT,
    "entryRequirementUgOutOf7" TEXT,
    "entryRequirementUgOutOf5" TEXT,
    "entryRequirementUgOutOf4" TEXT,
    "withoutMaths" BOOLEAN,
    "workExp" TEXT,
    "backlog" INTEGER,
    "backlogRange" TEXT,
    "fifteenYearsEducation" BOOLEAN,
    "scholarshipAvailable" BOOLEAN,
    "scholarshipDetail" TEXT,
    "internshipAvailable" BOOLEAN,
    "averageScholarship" DECIMAL(65,30),
    "averageScholarshipRemarks" TEXT,
    "eligibleCountryIds" INTEGER[],
    "eligibleCountryIdStudyLevelIds" TEXT[],
    "eligibleStateIds" INTEGER[],
    "commissionAmount" DECIMAL(65,30),
    "commissionMode" TEXT,
    "commissionCurrency" TEXT,
    "commissionToolTipMessage" TEXT,
    "increasedCommissions" JSONB,
    "remarks" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Program_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Program_sourceId_key" ON "Program"("sourceId");

-- CreateIndex
CREATE INDEX "Program_universityId_idx" ON "Program"("universityId");

-- AddForeignKey
ALTER TABLE "Program" ADD CONSTRAINT "Program_universityId_fkey" FOREIGN KEY ("universityId") REFERENCES "University"("id") ON DELETE CASCADE ON UPDATE CASCADE;
