/**
 * `npm run verify:completeness`
 *
 * Day-3 B3: prints the seven-question completeness matrix for all Phase 1
 * sources and writes `docs/ingestion/source-completeness.md`. Exits non-zero if
 * any source fails a check.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  CHECK_LABELS,
  checkAllSources,
  type SourceCompleteness,
} from "./sourceCompleteness";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, "../../../../..");
const OUTPUT = resolve(REPO_ROOT, "docs/ingestion/source-completeness.md");

const MARK = { PASS: "✓", FAIL: "✗", NOT_APPLICABLE: "–" } as const;

function pad(value: string, width: number): string {
  return value.length >= width ? value.slice(0, width) : value + " ".repeat(width - value.length);
}

function printMatrix(results: SourceCompleteness[]): void {
  console.log("\nDay-3 B3 — Phase 1 source completeness\n");
  console.log(
    pad("SOURCE", 34) + pad("GEO", 5) + CHECK_LABELS.map(([, label]) => pad(label, 14)).join("")
  );
  console.log("-".repeat(34 + 5 + CHECK_LABELS.length * 14));

  for (const result of results) {
    console.log(
      pad(result.code, 34) +
        pad(result.geo, 5) +
        CHECK_LABELS.map(([key]) => pad(MARK[result.checks[key].status], 14)).join("")
    );
  }

  const failing = results.filter((result) => !result.complete);
  if (failing.length === 0) return;

  console.log("\nFailures:\n");
  for (const result of failing) {
    for (const [key, label] of CHECK_LABELS) {
      const check = result.checks[key];
      if (check.status === "FAIL") console.log(`  ${result.code} · ${label}: ${check.detail}`);
    }
  }
}

function buildDocument(results: SourceCompleteness[]): string {
  const complete = results.filter((result) => result.complete).length;

  const header =
    `| Source | Geo | Family | Enabled | ${CHECK_LABELS.map(([, label]) => label).join(" | ")} |\n` +
    `| :--- | :--- | :--- | :--- | ${CHECK_LABELS.map(() => ":---:").join(" | ")} |`;

  const rows = results.map(
    (result) =>
      `| \`${result.code}\`<br>${result.name} | ${result.geo} | ${result.family} | ${
        result.enabled ? "yes" : "no"
      } | ${CHECK_LABELS.map(([key]) => MARK[result.checks[key].status]).join(" | ")} |`
  );

  const details = results
    .map((result) => {
      const lines = CHECK_LABELS.map(
        ([key, label]) =>
          `- **${label}** ${MARK[result.checks[key].status]} — ${result.checks[key].detail}`
      ).join("\n");
      return `### \`${result.code}\` — ${result.name}\n\n${lines}`;
    })
    .join("\n\n");

  return `# Phase 1 Source Completeness — Day 3 (B3)

> **Generated by \`npm run verify:completeness\`. Do not edit by hand.**

Every configured source is instantiated and its adapter methods are called with
a probe HTTP client that records the request and throws before a socket opens.
No live request is made, so this runs offline; it proves that discovery, detail
and healthcheck are wired to the configured official endpoint, not that the
endpoint is up. Use \`POST /api/admin/content-sources/:code/healthcheck\` from
the Admin source page for that.

- **Sources checked:** ${results.length}
- **Complete on all seven checks:** ${complete}
- **Legend:** ✓ pass · ✗ fail · – not applicable

## Matrix

${header}
${rows.join("\n")}

## Per-source detail

${details}
`;
}

async function main(): Promise<void> {
  const results = await checkAllSources();
  printMatrix(results);

  mkdirSync(dirname(OUTPUT), { recursive: true });
  writeFileSync(OUTPUT, buildDocument(results), "utf8");

  const failing = results.filter((result) => !result.complete);
  console.log(`\n✓ report written to ${OUTPUT}`);

  if (failing.length > 0) {
    console.error(`✗ ${failing.length} of ${results.length} sources are incomplete`);
    process.exitCode = 1;
    return;
  }
  console.log(`✓ all ${results.length} Phase 1 sources pass all seven checks`);
}

void main();
